### ISSUE TITLE
local Development - 'Access to process.binding('http_parser') is deprecated.'

### ISSUE THREAD

**Issue by AllanOcelot** [agileseason/agileseason#161]
Two small issues here:

1. I need to force an npm i via `npm i --force` to ensure dependencies work, as some are deprecated, 

2. After forcing an install, the following error is generated when attempted to run via `npm run serve` 
  `10% building 2/2 modules 0 active(node:23488) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)`

Hopefully this is a simple / quick one to resolve :)

**Comment by blackchestnut** [comment]
@AllanOcelot Unfortunately I can't reproduce the problem. I use `yarn`:
```
yarn
yarn serve
```

But... at the moment this app doesn't work by itself :( The web part needs a server API. Also, everything is complicated by the need to use github apps with fixed redirection urls, secret keys, etc. I wanted to write mocks/stubbed wrappers for API methods so that anyone could run the UI without a server. But it will take a lot of time.

**Comment by AllanOcelot** [comment]
Ah! No issue - if you ever get the time to fix it, feel free to ping me. 

I'm interested in seeing where this project goes!
